[pytest]
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::requests.exceptions.RequestsDependencyWarning
    ignore:.*python_multipart.*:PendingDeprecationWarning
    ignore:.*strip_cdata.*:DeprecationWarning
    ignore:fully NULL primary key identity cannot load any object:sqlalchemy.exc.SAWarning
