[pytest]
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::requests.exceptions.RequestsDependencyWarning
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning:bs4.*
    ignore:fully NULL primary key identity cannot load any object:sqlalchemy.exc.SAWarning
