"""change udemy_cookies column from JSON to Text

Revision ID: 0bd117e7d36c
Revises: 1c7670167de7
Create Date: 2026-07-03 21:45:03.918938
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0bd117e7d36c'
down_revision = '1c7670167de7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolled_courses', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('enrolled_courses', sa.Column('is_coupon_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrolled_courses', 'is_coupon_valid')
    op.drop_column('enrolled_courses', 'last_checked_at')
    # ### end Alembic commands ###
